# Use CentOS 7 Python to get a proper UTF-8 enabled environment
image: centos/python-35-centos7

pipelines:
  default:
    - step:
        script:
          - export LANG=en_US.UTF-8
          - pip install -U nikola
          - python --version
          - pip --version
          - nikola --version
          - pushd site
          - nikola build
          - popd
          - ls
