# Use Fedora 24 base image to get a proper UTF-8 enabled environment
image: fedora:24

pipelines:
  default:
    - step:
        script:
          - export LANG=C.UTF-8
          - python3 --version
          - pip3 --version
          - pip3 install --user -U 'nikola ~= 7.8'
          - nikola --version
          - pushd site
          - nikola build
          - popd
          - ls
