# Use Fedora 25 base image to get a proper UTF-8 enabled environment
# and a manylinux compatible version of pip
image: fedora:25

pipelines:
  # For PR branches, only do a test build
  default:
    - step:
        caches:
          - pip
          - deployed
        script:
          - export LANG=C.UTF-8
          - python3 --version
          - pip3 --version
          - pip3 install --user -U 'nikola ~= 7.8' markdown
          - ~/.local/bin/nikola --version
          - pushd site
          - ~/.local/bin/nikola build
          - popd
          - ls
  branches:
    # For the actual default branch, auto-deploy all changes
    default:
      - step:
          caches:
            - pip
            - deployed
          script:
            - dnf install -y git
            - git clone git@github.com:ncoghlan/ncoghlan.github.io.git deployed || (pushd deployed ; git pull; popd)
            - export LANG=C.UTF-8
            - python3 --version
            - pip3 --version
            - pip3 install --user -U 'nikola ~= 7.8' markdown
            - ~/.local/bin/nikola --version
            - pushd site
            - ~/.local/bin/nikola build
            - ~/.local/bin/nikola deploy publish-ci
            - popd
            - ls

definitions:
  caches:
    deployed: deployed
