# Use Fedora 25 base image to get a proper UTF-8 enabled environment
# and a manylinux compatible version of pip
image: fedora:25

pipelines:
  default:
    - step:
        caches:
          - pip
          - deployed
        script:
          - git clone git@github.com:ncoghlan/ncoghlan.github.io.git deployed
          - export LANG=C.UTF-8
          - python3 --version
          - pip3 --version
          - pip3 install --user -U 'nikola ~= 7.8' markdown
          - ~/.local/bin/nikola --version
          - pushd site
          - ~/.local/bin/nikola build
          - popd
          - ls

definitions:
  caches:
    deployed: deployed
